### ISSUE TITLE
スタンダード版／最適化版／ユニバーサル版の区別はユーザ視点から見た要求なのか実装方法か

### ISSUE THREAD

**Issue by murata2makoto** [Japan-Daisy-Consortium/Technical-Committee#1]
#2 #3 #4 #5

**Comment by t-kudou** [comment]
ユーザ視点では多くの場合には自分のPDに則した表示が行えるEPUBが発見できれば良く、それがスタンダード版なのか最適化版なのかユニバーサル版なのかという種別は問わないはずです。

しかし、学習に用いる本（教科書や語学学習書等）の場合、最初は総ルビ表示で読み、一定量の学習後に原本通りのルビ表示に切り替えて読みたい、あるいはルビ無しで読みたいといった要求があります。
このような場合には表示切り替えが期待できる最適化版やユニバーサル版が発見できる必要があります。

また、一つのEPUBから複数のPDに則した最適化版が製作できます。最適化版がどのような面で最適化されているかが判らないと、発見の際に間違ったEPUBを選択してしまいます。また、ユニバーサル版においてはどのような表示の切り替えが行えるかという定義を明確にすべきかもしれません。

**Comment by t-kudou** [comment]
こちらは #5 の議論につながります。

**Comment by kzakza** [comment]
[#2 で書いた意見](https://github.com/Japan-Daisy-Consortium/Technical-Committee/issues/2#issuecomment-695802328)でもありますが、スタンダード版／最適化版／ユニバーサル版の区別は、ルビとは別のメタデータ項目でさせたほうが良いかと思います。ただ、スタンダード版／最適化版／ユニバーサル版の区別のような区別が、海外であるのかどうか、それとも日本独自の要件なのか。後者だと、独自にメタデータ項目を新設することは、かなりハードルが高そうですね・・

**Comment by murata2makoto** [comment]
スタンダード版／最適化版／ユニバーサル版の区別は実装方法であって、ユーザ要求ではないという結論が出ているように思います。
