### ISSUE TITLE
原本が縦書き・横書き混在の場合、縦書表示にした場合に原本の横書き部分は縦書きにするべきか

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#10]
原本が縦書き・横書き混在の場合、これを縦書表示にした場合に原本の横書き部分は縦書きにするべきでしょうか。
あるいは横書き表示にした場合に、縦書き部分は横書きにするべきでしょうか。

**Comment by murata2makoto** [comment]
混在は出来ないというのが現状だと思います。混在したとき相互運用性のある形で運用するのは現状では無理という意味です。

少なくとも当面はいらないでしょう。。縦横混在のEPUBが頻出するようになるまで考える必要はないと思います。

**Comment by t-kudou** [comment]
技術委員会にて、縦書き・横書き混在については考慮しないとなりましたので、クローズします。
