### ISSUE TITLE
縦書きの行の並びは右から左のみでよいか

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#11]
縦書きの行の並びが左から右の順ということも考えられますが、右から左のみの想定でよいでしょうか。
これを逆順に変更したいというニーズは存在するでしょうか。

**Comment by murata2makoto** [comment]
想像もつきません。

**Comment by murata2makoto** [comment]
CSS縦書きだと、モンゴル語（内モンゴル）の縦書きのために入っています。やったことはありませんが、そのためのCSSスタイルシートを適用すれば日本語でも左から右になるはずです。CSS WGの領分であり本委員会の領分ではない、すでにCSSにあるという理由により、このissueはクローズします。
