### ISSUE TITLE
原本が縦書き・横書きかを示す情報

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#12]
本文中に「右図のように」のような表現があった場合には、特定のレイアウトを想定した表現になっていると思います。
リーディングシステムによって縦横の切り替え表示を行った場合に、このような表現の変更を行うのは困難だと思います。
原本が縦書きなのか、横書きなのかという情報がしっかり示されているならば、このような特定レイアウトを想定した文中の表現は読者が読み替えて理解できるという議論がありました。
原本が縦書き・横書き・縦横混在等はメタデータとして必要でしょうか。

**Comment by murata2makoto** [comment]
電子書籍の発見・検索に使わないのならメタデータで入れるまでのことはないと思います。

**Comment by t-kudou** [comment]
2020年10月24日の技術委員会の打ち合わせで話し合った内容を以下にまとめます。

・最適化版を作る場合、出版社が変更する場合いずれも、まじめに本文を修正すると仮定する
・縦・横のスタイルを持っているかという情報は必要

EPUBが縦・横の両方のスタイルを持っている場合、本文は縦書きを前提あるいは横書き前提のどちらかになっています。
特定の縦書き・横書きのレイアウトを前提とした記載内容については、読者はどちらか片方については読み替えを行わなければなりません。したがって、

・記載内容が縦書を前提としている
・記載内容が横書を前提としている

の情報が必要と考えます。
こちらは、文中にEPUB図書凡例として「この本は縦書きのレイアウトを前提としています」あるいは、「この本は横書きのレイアウトを前提としています」といった記載を設けることで対応できるだろうという話となりました。

確認ですが、これは、要求仕様や機構仕様のどちらに記載すべきことでしょうか。それとも記載しない方が良いものでしょうか。

**Comment by imagedrive** [comment]
> こちらは、文中にEPUB図書凡例として「この本は縦書きのレイアウトを前提としています」あるいは、「この本は横書きのレイアウトを前提としています」といった記載を設けることで対応できるだろうという話となりました。

本文だけでなく、accessibilitySummaryに書いて欲しいのですが、そうなると機構仕様になりますかね。

**Comment by t-kudou** [comment]
accessibilitySummaryに書くのであれば、何らかの記載を要求仕様も書くべきだと思います。
この点については明日の打ち合わせで協議させていただけたらと思います。

**Comment by t-kudou** [comment]
2020年10月24日の技術委員会の打ち合わせでは、「記載内容が縦書きのレイアウトを前提としている」、あるいは「記載内容が横書きのレイアウトを前提としている」という情報を必要とするという議論の流れとなりました。

音声のみでEPUBの本を読んでいる場合、スマホやタブレットで、スクリーンリーダーで画面の1行ずつ読み上げる場合、指を縦に順番に移動するのか、横に順番に移動するかで困る場合がありますが、このような情報があれば、迷うことがありません。
ただし、これはリーディングシステム側が縦書き表示をしているのか、横書き表示をしているのかは把握しているので、リーディングシステムの機能として実現できる可能性があります。

**Comment by t-kudou** [comment]
いらないという結論とする。

**Comment by murata2makoto** [comment]
理由を補足

いま読んでいる本が縦書きか横書きかは読者にもRSにも分かる。それで不満なら、もう一方のほうを探せばよい。

原本からどう変えたかは、本のどこかに書かれているだろうから、メタデータで原本が縦書きか横書きかは書く必要がない。

**Comment by murata2makoto** [comment]
原本が縦書きか横書きかは、読者に分かる形で文章として書かれるでしょうから、メタデータとしてはいらないという結論と理解しています。
