### ISSUE TITLE
縦組・横組を切り替えのできるEPUBの場合、どちらを優先するかという情報が必要か

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#13]
記載内容が縦組前提の内容なのか、横組前提の内容なのかを示す情報が必要性についての議論の中で、
縦組・横組を切り替えのできるEPUBの場合、どちらを優先するかという情報が必要ではないかという
問題提起がありました。

縦組・横組を切り替えのできるEPUBで、記載内容が縦組前提の内容なのに、横組を優先する場面は無いと
考えられます。
どちらを優先するかという情報は、記載内容が縦組前提の内容なのか、横組前提の内容なのかを示す情報
と兼用できるのではないでしょうか。

**Comment by kzakza** [comment]
工藤さんのご意見に同意します。記載内容が縦組/横組前提の内容なのかという情報（①）と、縦組/横組を優先するのか（②）という情報は兼用できると思います。

私はほぼ同じものと理解していました。

工藤さんのおっしゃる「前提」と「優先」の違いが私の認識と異なるもしれませんが、私は以下の様に理解しています。

現状、縦組・横組を切り替えのできるRSがありませんので、それを前提とするなら、作られたEPUBが横組/縦組なのかという情報（①）が必要ということになります。
しかし、縦組・横組を切り替えが自由にRSを前提とするなら、横組/縦組の表示の選択権はユーザー側にありますので、作り手である出版社は、横組/縦組という状態をメタデータとして示すことはできませんので、横組/縦組のどちらを最適化して作ったという情報（②）を提供するということになるのだろうと思いました。

**Comment by imagedrive** [comment]
RSがどの情報から縦・横組を判断しているのか分かりませんが、日本語の電子書籍の場合、spineのpage-progression-directionで組み方向の前提が判断できます。rtlなら縦組前提かつ優先だろうし、ltrなら横組でということになるのではないでしょうか。
ここであえてメタデータで定義するものが、単に組み方向だけでなく、テキストの表現なども含めてなら、安藤さんが言うような情報も追加で必要だと思います。

**Comment by t-kudou** [comment]
左綴じなら横組で、右綴じなら縦組というのは基本的な紙の本のルールのようですが、必ずしも成り立たないようです。
少し調べてみた所、
雑誌は横組なのに右綴じが多いそうです（例：non-no）。また、写真や画像が多いものは横組みでも右綴じが主流のようです。
また、page-progression-directionはめくり順を表現していますが、メタ情報ではないというのが難点です。

ちなみにボイス オブ デイジーではHTMLから参照されるCSSを調べて縦組か横組かを判定しています。
縦組の場合にはデイジー・EPUBの再生ボタンや移動の向きを▶から◀に変更したり、移動ボタンの配置を逆にしたり、ボタンのスクリーンリーダによる読み上げ内容を切り替えたり、ハイライト箇所の計算ロジックの縦横を切り替える等の処理を行っています。

ところで、今はメタ情報の役割は発見＝検索という所にフォーカスして議論していますが、メタ情報の役割は発見だけではないように思いいます。本の書誌に関する情報がメタ情報を通じて統一された方法で取得できるという面も重要です。その意味でも、縦組を前提としている記載なのか、横組を前提とした記載なのかを、メタ情報で取得できるのは重要だと考えます。

**Comment by imagedrive** [comment]
私が持っている雑誌（例：モデルグラフィックス）は縦と横の混在で右綴じです。ふくろうの本は図が多いですが、キャプション以外は縦組の右綴じです。美術展の図録は、手元にあるのはほぼ（基本）横組で左綴じでした。図鑑とか（例：産業革命歴史図鑑、ロンドン歴史図鑑）は、完全に横組で左綴じです。もっとも原書が英語だからだと思いますが。
上記に関しては、電子化において画像化されると思います。この話は画像化された電子書籍も含むのでしたっけ。
ただし、今後登場する可能性がある複雑な組版や縦横混在ページを処理できるRSを考えると、メタ情報に追加するのが良いと思います。

> メタ情報で取得できるのは重要だと考えます。

これは理解できます。一方で制作面で考えると、すでに存在する情報で事足りるのに、同じ目的の情報を追加するのはコストとエラーの懸念があります。
確かにspine要素はメタデータではありませんが、OPFですし、仕様には「The page-progression-direction attribute sets the global direction in which the content flows.」とあるので、今回の目的を果たすことができると思いました。meta要素でもspine要素でもパースすれば同じかなと。
EPUBアクセシビリティ仕様に、OPFで規定しているものを上書きするメタ情報ってありましたっけ？

とは言うものの、page-progression-direction属性は省略でき、省略された場合、default値としてlanguage要素を元にRSが判断する仕様なので、この事を想定するならば、やはりメタ情報で規定する必要があるかと思います。

**Comment by t-kudou** [comment]
要求としてはあるという結論

**Comment by t-kudou** [comment]
ONIXの場合はEPUB外部なので、メタ情報として入れては良い

**Comment by t-kudou** [comment]
2020年10月31日の技術委員会の議論にて、
こちらの要求を入れるという結論となりました。
