### ISSUE TITLE
縦組・横組について原文通りの表示が可能なEPUBを発見したいという要求はあるか

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#14]

**Comment by kzakza** [comment]
出版社にとっては、電子書籍というのは、紙でいうところの、文庫、文芸書のような、「版」（edtion）の違いであり、電子書籍版もオリジナルと考えると思いますので、「原文」というのは、分かりづらいような気もします。

**Comment by murata2makoto** [comment]
original or printed publications

**Comment by murata2makoto** [comment]
prinited or primary publication?

**Comment by t-kudou** [comment]
原本または印刷本、original（printed publication）という位置づけです。例を示して説明する。
底本というと紙になる。
印刷物または電子書籍を作る元になった出版物
用語については検討

この要求は無いという結論

**Comment by murata2makoto** [comment]
いま読んでいるものが縦なのか横なのかは分かるし、原本がどうだったかは文章として書かれるでしょう。それで不満なら、もう一方の組ができるものを捜せばよいということになったと理解しています。
