### ISSUE TITLE
縦組・横組発見機構仕様: assumedWritingDirectionではなくAlternateを使うべきでは

### ISSUE THREAD

**Issue by murata2makoto** [Japan-Daisy-Consortium/Technical-Committee#19]
Alternate Style Tagsでは、alternateというキーワードがrel属性に含まれているかどうかによって、主要な組方向かどうかを決定します。メタデータもそれに合わせて設計すべきではないでしょうか。

**Comment by t-kudou** [comment]
alternateを使うように仕様を修正しました。内容について本日の会議で合意が得られたので、クローズします。

**Comment by t-kudou** [comment]
前回2020年12月19日の技術委員会で、現行案だとalternateを使うメタデータの記法についてあり得ない組合せが記載可能である旨の指摘がありましたので、再度issueをオープンします。

■ 現行案
現行案は以下の通りです。複数回cjkWritingDirectionで始まるメタデータを記載する方法です。
注：タグを使った書き方はここに上手く記載できないようなので = を使って表記します。

・縦組表示が可能なEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/vertical-writing

・横組表示が可能なEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/horizontal-writing

・縦組表示・横組表示の両方が可能で、縦組が前提のEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/vertical-writing
schema:accessibilityFeature = cjkWritingDirection/alternate-horizontal-writing

・縦組表示・横組表示の両方が可能で、横組が前提のEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/horizontal-writing
schema:accessibilityFeature = cjkWritingDirection/alternate-vertical-writing

■ 見直し案
見直し案は、次の通りです。1個だけcjkWritingDirectionで始まるメタデータを記載する方法です。

・縦組表示が可能なEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/vertical-writing

・横組表示が可能なEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/horizontal-writing

・縦組表示・横組表示の両方が可能で、縦組が前提のEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/vertical-writing-alternate-horizontal-writing

・縦組表示・横組表示の両方が可能で、横組が前提のEPUBに対して付与するメタデータ
schema:accessibilityFeature = cjkWritingDirection/horizontal-writing-alternate-vertical-writing

■ Pros and Cons

Pros: 
見直し案はこの4通りの組合せしか許さないという形にでき、誤解が生じません。
現行案は、検索に関する実装に負担がかかりません。

Cons: 
見直し案は、縦組が可能な本の検索時に、vertical-writing、vertical-writing-alternate-horizontal-writing、horizontal-writing-alternate-vertical-writingの3つを検索しなければならない。正確な縦組が可能な本の検索時は、vertical-writing、vertical-writing-alternate-horizontal-writingの2つを検索しなければならない。
横組みの場合も同様です。
見直し案は、検索に関する実装に負担がかかります。
