### ISSUE TITLE
原本通りのルビかどうか

### ISSUE THREAD

**Issue by murata2makoto** [Japan-Daisy-Consortium/Technical-Committee#2]
ルビが原本通りかどうかというのは利用者にとって重要です。原本通りのルビで読めることは、社会でやってくための目標の一つになるからです。

総ルビ（または徹底的なパラルビ）で読めるようになった後に、原本通りのルビで読めるかどうか確認するということもあるでしょう。

したがって、原本通りのルビ表示が出来るものを探せることは重要です。

（賛成ならサムズアップしてください）

**Comment by kzakza** [comment]
今、読んでいるEPUBのルビが原本通りのルビなのか、いわゆる最適化版のルビなのかという情報は読む段階では、必要だと思います。つまり、読者は読む段階で以下の２つの情報は知りたいと考えると思います。

1. このEPUBのルビが原本どおりのルビなのか、最適化版のルビ表示なのか（ルビ追加 or ルビ除去）
2. （ルビ追加の最適化がなされたとして）どれが原本通りのルビでどれが最適化版で追加されたルビ

しかし、検索する段階では、スタンダード版/最適化版問わず、総ルビ、パラルビ、ルビなしのルビの状態を優先して検索したいのではないかと私は思います。

多分ですが、スタンダード版/最適化版ということを問題にする場合、最適化はルビだけに限られないと思います。そのため、メタデータも、スタンダード版/最適化版を区別できるメタデータが別に必要になるのではないかと。そして、原本通りの状態を探したいユーザーは、そちらのメタデータでスタンダー版の集合を作る検索条件で検索をすることになるのではないかと。

**Comment by t-kudou** [comment]
総ルビを必要としているPDの方が、はじめに総ルビ表示が可能な本を読み、次の段階として原本通りのルビの本を読みたいとします。（主に学習者がこのような読書方法を行います）
最初の時点の発見は、総ルビ表示が可能な本という条件です。この本を取得してリーディングシステムで読んだ後に、原本通りの表示ができないことに気がついた場合、次のステップは原本通りのルビの本の発見です。
原本通りのルビの発見手段が無い場合には、このような発見が行えないことになります。

また、健常者やルビに関して特別な配慮が不要なPDにとっては、原本通りのルビの本を発見したいという要求は確実に存在します。

**Comment by kzakza** [comment]
原本通りのルビの発見手段を求めるニーズはあると私も思います。

総ルビを必要としているPDの方の場合は、まずは以下の流れになると理解していますが、

1. 総ルビの本を探す
2. 原本通りのルビの本 を探す

２については、スタンダード版/最適化版を区別する目的に特化したメタデータで、スタンダード版にフラグの建てられたものに絞り込めば満たせるのではないかと考えた次第です。

ただ、最適化版にフラグが立っているEPUBでもルビは原本どおり（他のところが最適化されている）というケースもありえると思いますので、これだけは十分ではないかもしれません。

しかし、スタンダード版/最適化版の違いは、とても大きなものなので、その区別がメタデータ項目の中でしかできないという状態はユーザーにとっても分かりづらいのではないかと思いました（ユーザー視点では、メタデータの「ルビ」という項目を見たいと、スタンダード版/最適化版の違いがわからない、検索時に絞り込めないということになりますし）

**Comment by t-kudou** [comment]
原本通りのルビ表示が可能な本で探すと、スタンダード版以外にユニバーサル版が見つかることになります。
ユニバーサル版が見つかって困る、あるいはユニバーサル版とスタンダード版がメタデータから区別できないと困る場合があるかという点が争点になるように思います。

**Comment by murata2makoto** [comment]
いまは実装方法の議論はしていません。原本通りのルビを提供できるものを捜せというユーザ要求があるか？議論の対象はこの一点だけです。

**Comment by murata2makoto** [comment]
あると合意した。
