### ISSUE TITLE
分かち書き発見要求のオープンとクローズの区別は必要か

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#21]
児童書や低学年の教科書のように全角スペースで分かち書きされているものと、<wbr/>のようなタグで分かち書き位置を表現したものと2通り存在することになります。このような区別はニーズとしてあるかどうかという議論がこれまで欠けていました。
分かち書き発見要求でオープンとクローズの区別は必要でしょうか。

河村さんより、TVの字幕がオープンとクローズの違いがあり、オープンは画像に焼き付いた字幕で、クローズは必要に応じて字幕を表示できる仕組みであり、分かち書きについても似ているという指摘がありましたので、ここでは「オープンとクローズの区別」とさせていただいています。

**Comment by t-kudou** [comment]
区別はいらないという結論

**Comment by murata2makoto** [comment]
決め打ちの縦書き(alt style tagsを使わない縦書き）と、単なる縦書きを区別しないのと同じ。
