### ISSUE TITLE
原本よりルビが多いかどうか

### ISSUE THREAD

**Issue by murata2makoto** [Japan-Daisy-Consortium/Technical-Committee#3]
原本通りのルビでは読めない（少なくとも最初は読めない）という自覚がある利用者なら原本より多いルビを求めるでしょう。

原本よりルビが多いということは、総ルビであるかか、パラルビだけれど原本よりはルビが多いかのどちらか分けることができます。

総ルビ表示が出来るものを探せることは必要だと思います。すべての漢字にルビがついているというのは、利用者にとっては安心でしょう。

パラルビだけれど原本よりはルビが多い表示ができるものを探せることは重要でしょうか？たとえば、小学校2年までの漢字はルビをつけないが、それ以降はルビがついているものを探したいという必要性はありますか？

**Comment by kzakza** [comment]
パラルビだけれど原本よりはルビが多いことがメタデータレベルでわかる必要はあると思いますが、メタデータをキーにそのような集合を作りたい（それに限定して絞り込んで検索したい）というニーズがあるかどうかは、個人的には疑問です。もしそうであれば、「メタデータレベルでわかる必要」に対応するのであれば、注記でどのあたりが原本と異なるのかを自然文で説明して対応することになるのではないかと思います。

**Comment by murata2makoto** [comment]
@kzakza 

以前に合意したメタデータ設計原則に照らせば「パラルビだけれど原本よりはルビが多いこと」を明示するメタデータは要らないということですね。

•	メタデータの付与コストを上回るメリットがあること
•	電子図書館・電子書店での検索に役立つこと
•	提供者が悩まずに付与できること
•	利用者にとって分かりやすいこと
•	国際的に受け入れられるものであること。とくに、台湾 、香港 、中国に配慮すること。

**Comment by t-kudou** [comment]
スタンダード版に対して一括して総ルビを付与するのは大変なので、部分的にルビを付与するというは製作側の事情としては十分に有り得ると思います。
また、仕様では音声合成による音声化は考慮しないことになっていますが、簡単なはずの読みでも、音声合成エンジンが読み間違いをしてしまうため、部分的にルビを付与する対応を行う製作者も出てくるように思います。
原本よりもルビが多いかどうかを仕様にふくめないとすると、このようにして製作されたEPUBに適切なメタ情報を付与できなくなる恐れがあります。

**Comment by murata2makoto** [comment]
@t-kudou 

>スタンダード版に対して一括して総ルビを付与するのは大変なので、部分的にルビを付与するというは製作側の事情としては十分に有り得ると思います。

これは、「パラルビだけれど原本よりはルビが多い」という事態はあるという主張であって、「パラルビだけれど原本よりはルビが多い」ことをメタデータで明示する必要があるという主張にはなりません。

> また、仕様では音声合成による音声化は考慮しないことになっていますが、簡単なはずの読みでも、音声合成エンジンが読み間違いをしてしまうため、部分的にルビを付与する対応を行う製作者も出てくるように思います。

これも同様です。

**Comment by t-kudou** [comment]
製作者が原本に対して部分的にルビを付与した最適化版を作るというのは、ユーザ（本の読み手）の発見に関する要求仕様ではないという点については同意します。

PDの要求としてルビ表示が欲しいという単純な要求があります。このとき、必ずしも総ルビでなくても良いという事情はどうでしょうか。たとえば小学校低学年で学習する漢字についてはルビは不要だが、それより上の学年で学習する漢字についてはルビが無いと困るといったものです。

**Comment by murata2makoto** [comment]
入れない。
自然言語でメタデータ中にかけば

**Comment by t-kudou** [comment]
技術委員会の結論としては、部分ルビはメタデータとしては付与しない。
自然言語で記述できればよい。

**Comment by kzakza** [comment]
委員会の結論に同意します（本日の会議にほとんど参加できずに申し訳ありませんでした　汗）。

メタデータの役割としては以下の2つがあると考えますが

1. 検索時に集合として絞り込むためのキーとして利用する 
2. 検索後に書誌画面を見る際にメタデータとして利用者に対象資料の情報を提供する（実際に資料を利用する前に対象資料の必要な情報を提供する）。

パラルビだけれど原本よりはルビが多いことがメタデータレベルでわかる必要はあると考えますが、本件に関しては、パラルビだけれど原本よりはルビが多いものに絞り込んで検索したいニーズはないとは言えませんが、高くはないと思います。2のニーズは満たす必要があると思いますが、2を満たすのみであれば、注記（自然言語による説明）でよいと考えます。
