### ISSUE TITLE
原本よりルビが少ないかどうか

### ISSUE THREAD

**Issue by murata2makoto** [Japan-Daisy-Consortium/Technical-Committee#4]
ルビがあると読みにくくなるタイプのディスレクシアには、原本よりルビが少なく表示されることを求める人もいるでしょう。

原本よりルビが少ないということは、ルビがないか、パラルビだけれど原本よりはルビが少ないかのどちらか分けることができます。

ルビなし表示が出来るものを探せることは重要でしょうか？

パラルビだけれど原本よりはルビが少ないい表示が出来るものを探せることは重要でしょうか？

**Comment by t-kudou** [comment]
ルビがあると読みにくいPDにとって、ルビが表示されないことで多くの要求は満たせると考えます。
ただし、リーディングシステムによって義訓やインラインアノテーション等は括弧書き等で表示されるという条件が伴うと思います。
義訓やインラインアノテーションが表示されないと、重要な情報が欠落することになります。

ルビを少なく表示して欲しいという具体的な要求としては、例えば小学校3年生の教科書で、小学校1年、2年で学習する漢字についてはルビを付けない表示が欲しいというものがありますが、これはスタンダード版（原本）よりも少なくして欲しいという要求ではなく、総ルビ表示よりも少なくして欲しいという要求になると思います。

**Comment by murata2makoto** [comment]
表示方法のこと（そして個々のルビ・行間注ごとに変わること）は、ここでは議論しないことにしましょう。文書全体についての発見・検索のことだけです。

> これはスタンダード版（原本）よりも少なくして欲しいという要求ではなく、総ルビ表示よりも少なくして欲しいという要求になると思います。

ということは、「パラルビだけれど原本よりはルビが少ない表示が出来るもの」を探せる必要はないということですね。

**Comment by t-kudou** [comment]
原本が総ルビの本に対して、ルビがあると読みにくいPD向けに難読漢字以外はルビを除去した最適化版を作るという要求は有り得ます。

**Comment by murata2makoto** [comment]
@t-kudou 

>原本が総ルビの本に対して、ルビがあると読みにくいPD向けに難読漢字以外はルビを除去した最適化版を作るという要求は有り得ます。

これも、こういう本はありうるという主張であって、こういう本だけを検索する必要があるという主張ではありません。

**Comment by murata2makoto** [comment]
メタデータ中の自然言語表記でいい

入れない

**Comment by kzakza** [comment]
[#3で書いた意見](https://github.com/Japan-Daisy-Consortium/Technical-Committee/issues/3#issuecomment-699508681)と同様です。
