### ISSUE TITLE
総ルビ表示・パラルビ表示・ルビなし表示の切り替え

### ISSUE THREAD

**Issue by murata2makoto** [Japan-Daisy-Consortium/Technical-Committee#5]
総ルビ表示・パラルビ表示・ルビなし表示のいずれも可能な本を探したいというのはユーザ要求でしょうか。それとも、総ルビ表示が可能な本を探すというユーザ要求、、パラルビ表示が可能な本を探すというユーザ要求、ルビなし表示のいずれも可能な本を探すというユーザ要求の三つがあるだけでしょうか。

**Comment by t-kudou** [comment]
ルビが無いと困るPDにとっては、総ルビ表示が可能な本を探したいというのが最優先です。次善の候補として部分ルビ表示が可能な本になります。ルビ無しの最適化版は一番読みにくいので避けるべき本です。使用するリーディングシステムがルビの表示・非表示の切り替え機能を有していて、ルビ無し表示が可能なユニバーサル版は避けるべき対象ではありません。
ルビがあると困るPDにとっては、ルビ無しの本が探せる必要があります。使用するリーディングシステムがルビの表示・非表示の切り替え機能を有しているならば、ルビ無し表示が可能な本を探せる必要があります。

ポイントは、
・総ルビの本と、総ルビ表示の可能な本は異なる
・部分ルビの本と、部分ルビ表示の可能な本は異なる
・ルビ無しの本と、ルビ無し表示の可能な本は異なる

という観点です。○○表示が可能な本は、使用するリーディングシステムが表示・非表示切り替えの機能を有している場合に条件に含まれるあるいは含まれないという区分けが必要になります。

**Comment by murata2makoto** [comment]
実装によって出来ることが違うというのはその通りです。しかし、「総ルビ表示がどの実装でもできる」と「総ルビ表示への切り替えに対応した実装なら総ルビ表示できる」をメタデータで区別すべきでしょうか？ 規格というものは単純にしておき、実装がやがて改善されることに期待するのがよいと思います。

**Comment by t-kudou** [comment]
使用しているリーディングシステムがルビの表示切り替え機能を有しているかどうかに則して、発見の優先順位を変えるというは標準仕様として難しそうだなとは薄々感じています。

リーディングシステムはルビ表示切り替えの機能を必ず有しているという前提で、メタデータを設計して良いということでしょうか。

**Comment by murata2makoto** [comment]
> リーディングシステムはルビ表示切り替えの機能を必ず有しているという前提で、メタデータを設計して良いということでしょうか。

私はそう思います。

**Comment by t-kudou** [comment]
この前提を置くならば、仕様はもう少しシンプルにできそうです。
スタンダード版、最適化版、ユニバーサル版という枠組みを持ち込む必要があったのも、リーディングシステムはルビ表示切り替えの機能を有していないかもしれないという縛りがあったためです。

リーディングシステムはルビ表示切り替えの機能を必ず有しているならば、スタンダード版、最適化版、ユニバーサル版という枠組みを使わずに、ルビの発見要求は次の４つのフラグに絞れるように考えます。

・原本通りのルビ表示が可能か
・総ルビ表示が可能か
・部分ルビの表示が可能か
・ルビの非表示が可能か

このフラグを使えば、スタンダード版、最適化版、ユニバーサル版の区別はこのフラグで全て示せると考えます。

◆ スタンダード版

・原本通りのルビ表示が可能か	YES
・総ルビ表示が可能か	原本が総ルビのものはYES, それ以外はNO
・部分ルビの表示が可能か	原本が部分ルビのものはYES, それ以外はNO
・ルビの非表示が可能か	原本がまったくルビなしのものはYES, それ以外はNO

◆ 最適化版

・原本通りのルビ表示が可能か	NO
・総ルビ表示が可能か	総ルビに最適化したものはYES, それ以外はNO
・部分ルビの表示が可能か	部分ルビに最適化したものはYES, それ以外はNO
・ルビの非表示が可能か	ルビを削除した最適化版はYES, それ以外はNO

◆ ユニバーサル版

・原本通りのルビ表示が可能か	YES
・総ルビ表示が可能か	総ルビの情報を持つユニバーサル版はYES, それ以外はNO
・部分ルビの表示が可能か	部分ルビの情報を持つユニバーサル版はYES, それ以外はNO
・ルビの非表示が可能か	ルビを非表示にする情報を持つユニバーサル版はYES, それ以外はNO

**Comment by t-kudou** [comment]
スタンダード版、最適化版、ユニバーサル版という枠組みを使わずに、ルビの発見要求は次の４つの項目に絞った形で、発見要求仕様を修正します。

・原本通りのルビ表示が可能か
・総ルビ表示が可能か
・部分ルビの表示が可能か
・ルビの非表示が可能か

**Comment by kzakza** [comment]
「スタンダード版、最適化版、ユニバーサル版」の区別は、ルビではなく、メタデータとしても他の項目で区別させるべきではないかと考えますので、「スタンダード版、最適化版、ユニバーサル版という枠組みを使わず」というご意見に同意します。

メタデータとして、ルビに提供が求められる情報は対象となるEPUBの状態(state)だと思います。そこに焦点を合わせるならば、以下ではないかと考えます。

・総ルビ
・部分ルビ
・ルビなし

　工藤さんのご意見で気になったのは、「原本通りのルビ表示」に総ルビ、部分ルビ、ルビなしの3つの状態がありえますので、きれいに住み分けられないところです。「原本通りのルビ表示」ということを表す場合も、総ルビ、部分ルビ、ルビなしの情報を提供するメタデータ項目とは別のメタデータ項目で表す必要があるのではないかと思いました。

　また、工藤さんの「可能か」ですが、「リーディングシステムはルビ表示切り替えの機能を必ず有しているという前提」に立つならば、「可能か」ではなく、そのような機能をRSが備えるために「可能な情報をメタデータとして持っているかどうか」になるのだろうと思います。RSにルビの切り替え機能があるのであれば、総ルビ本→ルビなし本、部分ルビ本→ルビなし本の切り替えは、メタデータ有無によらず可能なはずです。

総ルビ本→部分ルビ本
総ルビ、部分ルビ、ルビなし→原本どおり

が可能かどうかは、個々のルビタグに切り替えに必要な情報が属性として記述されていないと、RSも判別できないと思いますので、そのような属性が埋め込まれていることが前提になるのだろうと思うのですが、メタデータとして表すならば、それの有無をメタデータとして記述することになるのでしょうか？

**Comment by t-kudou** [comment]
私の整理では、
・原本通りのルビ表示が可能か
・総ルビ表示が可能か
・部分ルビの表示が可能か
・ルビの非表示が可能か
の4つの項目を使うと、

原本が総ルビのスタンダード版は、原本通りのルビ表示が可能、総ルビ表示が可能
原本がルビ無しのスタンダード版は、原本通りのルビ表示が可能、ルビ無し表示が可能
原本が部分ルビのスタンダード版は、原本通りのルビ表示が可能、部分ルビ表示が可能
総ルビの最適化版は、総ルビ表示が可能
部分ルビの最適化版は、部分ルビ表示が可能
ルビ無しの最適化版は、ルビ無し表示が可能
ユニバーサル版で、総ルビに対応したものは、原本通りのルビ表示が可能、総ルビ表示が可能
ユニバーサル版で、部分ルビに対応したものは、原本通りのルビ表示が可能、部分ルビ表示が可能
ユニバーサル版で、ルビ非表示に対応したものは、原本通りのルビ表示が可能、ルビ非表示が可能
ユニバーサル版で、総ルビ、部分ルビ、ルビ非表示に対応したものは、原本通りのルビ表示が可能、総ルビ表示が可能、部分ルビ表示が可能、ルビ非表示が可能

となります。（本日の議論では部分ルビは無くなるという結論ですが）
このシンプルな要求の表現方法でこれまで考えた全てのパターンを網羅できます。
本日の議論では、この整理内容については要求仕様では言及しないという結論になりました。

また、各EPUBにはそれぞれ、
・原本通りのルビ表示が可能かを表現する情報
・総ルビ表示が可能かを表現する情報
・部分ルビの表示が可能かを表現する情報
・ルビの非表示が可能かを表現する情報
を持たせる必要があります。しかし、この部分は発見要求仕様ではなく、発見機構仕様で言及すべき項目と考えます。
具体的な機構の私案は、先ほどお送りした発見機構仕様 version 0.1をご覧ください。
一応この機構仕様の私案も念頭に要求仕様を修正し、version 0.6としました。

**Comment by murata2makoto** [comment]
皆さんの議論を見ると、

・原本通りのルビ表示が可能な本を探すというユーザ要求
・総ルビ表示が可能な本を探すというユーザ要求
・部分ルビの表示が可能な本を探すというユーザ要求
・ルビの非表示が可能な本を探すというユーザ要求

の四つがユーザ要求であるという合意が出来ているように思えます。

**Comment by kzakza** [comment]
その点は同意です。

**Comment by murata2makoto** [comment]
・原本通りのルビ表示が可能な本を探すというユーザ要求（原本が総ルビ、パラルビ、ルビなしなのかを問わず）
・総ルビ表示が可能な本を探すというユーザ要求
・部分ルビの表示が可能な本を探すというユーザ要求
・ルビの非表示が可能な本を探すというユーザ要求
