### ISSUE TITLE
ルビ発見機構でパラルビについては自然言語で記述するべきか

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#6]
前前回のAdHoc会議ではパラルビに関しては自然言語で記述できれば良いという意見がありました。
<meta property="schema:accessibilityFeature">rubyAnnotations/para</meta>
のような指定方法で良いでしょうか。

**Comment by kzakza** [comment]
自然言語、というというは、accessibilitySummaryでということでしたか？

rubyAnnotations/paraと言う形で、fullとnoneと並ぶ形でパラルビの状態を示す値は必要だと思います。

メタデータは、検索キーに用いることも一つの用途ですが、対象となる資料やデータを整理された形でユーザーに伝えることも大きな役割です。
検索キーでパラルビを指定するケースはあまりないかもしれませんが、あるタイトルのEPUBの書誌詳細画面にたどり着いたときに（書誌詳細画面というのはサピエでいれば、[サピエ図書館　資料詳細](https://library.sapie.or.jp/cgi-bin/CN1MN1?S00101=J00DTL04&S00222=3317844)という画面です）に、この画面でデータを開く前にパラルビであるということがわかることに意味があると思いますので、accessibilitySummaryのみでは不十分と考えます。

また、rubyAnnotationsでfullとnoneを用意するのであれば、ルビの状態を示す値に穴があってはいけない（そのメタデータでルビの状態を網羅できないのは避けたほうがよい）とおもいますので、その意味でも必要だろうと思います。

**Comment by t-kudou** [comment]
rubyAnnotations/para のみでは不十分ではないかとの問題意識でこのissueを立ち上げました。
ではaccessibilitySummaryにどのようにパラルビについて記載すべきかという例もルビ発見機構仕様の中に加えた方が良さそうですね。

**Comment by t-kudou** [comment]
以下に、解説がありました。
https://schema.org/accessibilitySummary
http://kb.daisy.org/publishing/docs/metadata/schema.org/accessibilitySummary.html
次のように複数言語で記載することもできるようです。
    <meta property="schema:accessibilitySummary" xml:lang="en">
        
    </meta>
    <meta property="schema:accessibilitySummary" xml:lang="fr">
        
    </meta>
パラルビのメタデータの記載例ではどの自然言語で記載されているかもしっかりと明示するのが良さそうです。

**Comment by kzakza** [comment]
rubyAnnotations/para がある前提で、自然言語でというお話だったのですね。失礼しました。そのお話なら異論ありません。

**Comment by imagedrive** [comment]
主題と脱線しますが、rubyAnnotations/paraを指定するなら、accessibilitySummaryによる補足は必要だと思います。
rubyAnnotations/originalを併記しても、特に教科書であればなおさらでしょう。

**Comment by t-kudou** [comment]
異論が無いようなので、自然言語で記述するという結論でクローズします。
