### ISSUE TITLE
ルビ発見機構における○○表示が可能という表現に追加の説明は必要か

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#7]
これまでの議論で、ルビ発見機構では次の表現で説明しています。
・総ルビ表示が可能なEPUBが発見できること
・パラルビ表示が可能なEPUBが発見できること
・ルビの非表示が可能なEPUBが発見できること
・原本通りのルビ表示が可能なEPUBが発見できること
JDCの技術委員会内では、例えば「総ルビ表示が可能なEPUB」と「総ルビのEPUB」は異なるという共通理解が得られていると考えています。前者は、スタンダード版として総ルビで作られたもの、総ルビの最適化版、総ルビのできるユニバーサル版等です。後者は、スタンダード版として総ルビで作られたものと総ルビの最適化版です。
この違いは重要な部分であるものの、誤解が生じうる部分と考えています。この○○表示が可能という表現に、ルビ発見機構仕様の中で追加説明は必要でしょうか。
追加説明をしようとするとどうしてもスタンダード版、最適化版、ユニバーサル版といった概念に言及せざるを得ないので悩ましい部分です。
あるいはルビ発見機構仕様とは別の全体の解説文書あるいはチュートリアルのようなものの中で説明すべきものでしょうか。
ご意見をお聞かせください。

**Comment by imagedrive** [comment]
> 総ルビの最適化版
この表現は違和感があるのですが、ルビがないと読むことが困難なので総ルビにしたという意味であれば、「最適化版としての総ルビ」「総ルビとしての最適化版」などでは如何でしょう。
「総ルビの最適化版」だと、総ルビに対して何かしら最適化したような印象を受けたもので。

> この違いは重要な部分であるものの
たしかにRSを通して表示されたものなのか、コンテンツなのかは明確にするのが誤解を招かないと思うので、おっしゃる通り、追加説明があったほうがよいと思います。
あちこちで使いそうなので、別途解説文書で良いのではないでしょうか。また、同様に使われるスタンダード版の表現を含めると各ドキュメントがすっきりしそうな気がします。

**Comment by kzakza** [comment]
（正直申し上げると、未だに区別がついていないかもしれません　汗）「スタンダード版として総ルビで作られたもの」と「総ルビの最適化版」は、ルビの状態としては総ルビですが、以下の違いがあり、メタデータとしては以下のように記述するという理解でよいのでしょうか（機構要求は1行でかけるのでver 0.1のものを用います。）。

- 「スタンダード版として総ルビで作られたもの」: 原本どおりのルビの表記→rubyAnnotations/full+orignal
- 「総ルビの最適化版」: 原本は総ルビではないが、総ルビをつけて最適化版になったもの→rubyAnnotations/full

「orignal」（standardでのよいのですが）がつかない「rubyAnnotations/full」が最適化版を指すというのは違和感があるのですが、orignalがない状態が何を指すのかも詰めておかないといけませんね。

**Comment by murata2makoto** [comment]
要求仕様書で実現機構に深入りすることは禁物です。スタンダード版、最適化版、ユニバーサル版という言葉を入れるべきではないと思います。

以下の注ではどうでしょう。

パラルビ表示が可能なEPUBを発見することとは、パラルビ表示しかできないEPUBを発見するということではない。ひとつのEPUBに対して総ルビ表示・パラルビ表示・ルビなし表示のいずれも可能ということは有り得るからである。

**Comment by kzakza** [comment]
要求仕様とは別の解説書で解説するという想定でした。WCAGで言うところの、 Understanding WCAG 2.0かTechniques for WCAG 2.0 のような。

**Comment by murata2makoto** [comment]
要求仕様とは別のところで、日本の関係者向けの説明は必要になるでしょうね。大量の例も含めて。

**Comment by t-kudou** [comment]
要求仕様とは別の日本向けの説明を作成するということで、クローズにします。
