### ISSUE TITLE
わかち書きされていると読みにくいPDが存在するか

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#8]
わかち書き発見要求で、わかち書きされていないEPUBを探したいというニーズがあるかが検討事項になりそうです。
その前提として、わかち書きされていると読みにくいというPDFが存在するかが焦点になると思いますが、存在するでしょうか。
健常者だと、わかち書きされていると読みにくいという方はいるかもしれません。

**Comment by murata2makoto** [comment]
分かち書きしない表示が可能な本を探したいというユーザ要求ですね？

**Comment by t-kudou** [comment]
存在するという結論

**Comment by t-kudou** [comment]
2020年10月10日の技術委員会で結論が出ていますのでクローズします。
