### ISSUE TITLE
わかち書きの方法に関する発見要求

### ISSUE THREAD

**Issue by t-kudou** [Japan-Daisy-Consortium/Technical-Committee#9]
わかち書きの方式は様々なバリエーションが存在すると思います。
たとえば、助詞の前で分かち書きしたEPUBを発見したいというニーズは存在しそうです。
分かち書きの方法を指定して発見したいという要求はあるでしょうか。

**Comment by murata2makoto** [comment]
うーん、名詞と助詞の間で分かち書きした本を探したいというユーザニーズはあるかも知れない。

**Comment by t-kudou** [comment]
特定の分かち書き方法のものを発見したいというニーズを発見要求に含めるかを議論できればと思います。
個人的には分かち書きのEPUBを見つけて、この本の分かち書きがどのような方法・流儀によるものかが自然言語で記載されていれば十分ではないかと考えています。

**Comment by t-kudou** [comment]
2020年10月24日の技術委員会では以下のようになりました。

リーディングシステムが勝手にできることは無くても良い
既に分かち書きされている出版物は存在する
わかち書きの表示要求仕様は日本語は作るが、英語は作らない
作業仮説： 
EPUBリーディングシステムは自動的に分かち書きをする機能があると仮定する。さらに、助詞の前での分かち書きなど、色々なやりかたの分かち書きもできる。
人間の加えた分かちで足りない部分は、機械で補える
#9の分かち書きの方法は発見要求にはふくめない。

結論が出たので、クローズします。
